### ISSUE TITLE
Bug in openresty requires?

### ISSUE THREAD

**Issue by p0pr0ck5** [openresty/opm#11]
I have installed opm manually to `/usr/local/openresty/bin/opm`. Trying to build a project with opm with the following line in dist.ini:

`requires = openresty > 1.9.7.3`

Results in build failure:

<pre>poprocks@soter:~/code/Lua/lua-resty-waf$ /usr/local/openresty/bin/opm build
found license: GNU General Public License (GPL) version 3.
ERROR: openresty is required but is not available according to resty:  at /usr/local/openresty/bin/opm line 2130.
</pre>

Ideas for troubleshooting? Tangentially, having opm available with `Carp` for debugging issues could be useful as well ;)

**Comment by p0pr0ck5** [comment]
Bah, ignore me. I need to read first. resty is undefined from `init_installation_ctx`.

It might still be worth adding some documentation to opm describing cases where builds or such may fail because the `resty` bin is undefined? Or shall we assume that all opm users have `resty` in PATH? Either way is good for me, just food for thought. Cheers!

**Comment by agentzh** [comment]
You have no /usr/local/openresty/bin/resty ? The opm tool first looks at that path before falling back to PATH as the last resort.

And yes, the error message deserves better.

**Comment by agentzh** [comment]
@p0pr0ck5 On my side, the error message is not too bad:

```
found license: BSD 2-Clause "Simplified" or "FreeBSD" license, GNU General Public License (GPL) version 2.
sh: resty: command not found
ERROR: luajit is required but is not available according to resty:
```

**Comment by agentzh** [comment]
@p0pr0ck5 To reproduce that, I renamed `/usr/local/openresty/bin/resty` to something else. BTW, are you using an old OpenResty without the `resty` utility?

**Comment by agentzh** [comment]
I've just made the error message a bit nicer by removing the "at /path/blah/blah" suffix.

**Comment by yxw55001100** [comment]
sudo ln -s 'pwd'/resty /usr/local/bin/resty
