### ISSUE TITLE
Character Encoding Issues with opm client

### ISSUE THREAD

**Issue by bungle** [openresty/opm#12]
It seems that opm.openresty.org doesn't correctly handle UTF-8.

![screen shot 2016-09-30 at 11 25 34](https://cloud.githubusercontent.com/assets/983257/18985449/a3822824-8700-11e6-9f18-dcf16391b97e.png)

See that `â`.

**Comment by agentzh** [comment]
Yeah, I've noticed that too. Will look into it today. Thanks for the report!

**Comment by agentzh** [comment]
@bungle Just committed a patch that fixes the UTF-8 problem in commit 19dc8f5e21. Also pushed it to the package server. Please try it again on your side. Thanks!

**Comment by agentzh** [comment]
@bungle I've just added explicit UTF-8 validity checks for "abstract" and "author" fields in dist.ini, both on the client and server side. Invalid UTF-8 sequences in these fields won't pass `opm build` or `opm server-build` :)

**Comment by bungle** [comment]
It seems the web site is now ok, but the client is not:

![screen shot 2016-10-03 at 22 37 00](https://cloud.githubusercontent.com/assets/983257/19051086/22442476-89ba-11e6-95a3-a4a9b32e7648.png)

**Comment by bungle** [comment]
`opm info` works fine, but it seems the search doesn't. Is this some kind of a caching issue?

**Comment by agentzh** [comment]
@bungle Well, this is actually another issue: `opm search` may pick up an abstract string from whatever releases with the same package name. So what you are seeing is just that `opm search` picks up your older release which has bad data in the database.

Well, I've just manually updated the database and fixed the encoding issue in your first lua-resty-session version.
