### ISSUE TITLE
Re-uploading packages

### ISSUE THREAD

**Issue by pintsized** [openresty/opm#13]
Is it possible to force upload the same package version again? I uploaded `lua-resty-redis-connector`, and then noticed that "core" modules are also available via opm, so decided to add `openresty/lua-resty-redis` as a dependency.  But it doesn't seem to allow me to re-upload, presumably without bumping the module version?

```
[jhurst@sl6 lua-resty-redis-connector]$ opm upload
found license: BSD 2-Clause "Simplified" or "FreeBSD" license.
Package lua-resty-redis-0.25 already installed.
extracted verson number 0.03 from main_module file lib/resty/redis/connector.lua.
lua-resty-redis-connector-0.03/
lua-resty-redis-connector-0.03/README.md
lua-resty-redis-connector-0.03/dist.ini
lua-resty-redis-connector-0.03/lib/
lua-resty-redis-connector-0.03/lib/resty/
lua-resty-redis-connector-0.03/lib/resty/redis/
lua-resty-redis-connector-0.03/lib/resty/redis/connector.lua
lua-resty-redis-connector-0.03/lib/resty/redis/sentinel.lua
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Date: Fri, 30 Sep 2016 09:29:00 GMT
Server: openresty
Content-Length: 112
Connection: keep-alive

ERROR: duplicate upload: lua-resty-redis-connector-0.03 (previously uploaded at 2016-09-30 09:05:17.767804+00).
```

**Comment by agentzh** [comment]
No, it's not allowed to override an indexed package of the same version number. This is by design to avoid security issues and also user confusion. Once a release is made and indexed, it's history. Any further changes need version number bump.

Having said that, you can still upload the exactly same version package when previous uploads all fail to index :)

**Comment by agentzh** [comment]
@pintsized BTW, it's generally not a good idea to require standard OpenResty libraries unless you have a specific version requirement on that standard library ;)

**Comment by pintsized** [comment]
@agentzh Ah, ok, makes sense. 

Good to know about the standard libraries - once I saw them there I wondered if in the future it might be necessary to install them manually as required.
