### ISSUE TITLE
Remove incorrect uploads

### ISSUE THREAD

**Issue by p0pr0ck5** [openresty/opm#14]
Is there a mechanism to remove packages that have been incorrectly uploaded? I forgot to correct the `name` attribute in my first upload of lua-ffi-libinjection (the upload time is tagged as `2016-09-30 16:46:58.760523+00`) when copying a boilerplate dist.ini.

**Comment by agentzh** [comment]
@p0pr0ck5 No, there is no such mechanism yet. Also, for security reasons, we usually do not want to provide an Internet-accessible way to remove packages on our server. Well, just send me a note offline in a private email and I can remove it for you.

**Comment by p0pr0ck5** [comment]
Sure, makes sense for now. I'd guess eventually we'll have some authorization mechanisms in place? For now I'll just learn to double check my uploads ;)

**Comment by agentzh** [comment]
We already have authorization based on the personal GitHub token. But for dangerous operations like removal, we need stronger ways like email verification and etc. Regarding your mistake here, I think we can make opm check that the name field matches the project part in the repo link.

**Comment by agentzh** [comment]
@p0pr0ck5 I've just committed a change that implements the repo_link vs name check. Please upgrade your local `opm` script. Thank you :) (BTW, the package server also does this check during indexing now).
