### ISSUE TITLE
curl failed!

### ISSUE THREAD

**Issue by lilien1010** [openresty/opm#15]
curl: (52) Empty reply from server
ERROR: failed to run command curl -sS -i -A 'opm 0.0.1 (darwin-thread-multi-2level, perl v5.18.2)' -H 'X-File: lua-resty-s3uploader-1.1.1.tar.gz' -H 'X-File-Checksum: ce5d56b670a82c43dd10bf4d1bc9da5f' -H 'X-Account: lilien1010' -H 'X-Token: **********' -T 'lua-resty-s3uploader-1.1.1.tar.gz' 'https://opm.openresty.org/api/pkg/upload'

**Comment by agentzh** [comment]
@lilien1010 I didn't see any related error logs on the server side. Have tried multiple times?

Also, what is the output of the command `curl https://opm.openresty.org/|grep pgmoon` on your side?

**Comment by agentzh** [comment]
@lilien1010 Also, please try specify the `--verbose` option of your `opm upload` command, so that we can have more details from `curl`.

**Comment by agentzh** [comment]
@lilien1010 FYI, I just tried `opm upload` on my Mac OS X 10.11.6 with the default system curl `/usr/bin/curl` in my macbook pro and it works for me when uploading to the real opm.openresty.org server.

**Comment by lilien1010** [comment]
when I run
`sudo opm upload --verbose
`

It shows a lot of info  like this 

`a lua-resty-s3uploader-1.1.1/lib/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match/README.md
a lua-resty-s3uploader-1.1.1/lib/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/cuint/History.md
a lua-resty-s3uploader-1.1.1/lib/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/cuint/README.md
a lua-resty-s3uploader-1.1.1/lib/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/commander/Readme.md
a lua-resty-s3uploader-1.1.1/lib/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/chromium-pickle-js/README.md
curl: (52) Empty reply from server
ERROR: failed to run command curl -sS -i -A 'opm 0.0.1 (darwin-thread-multi-2level, perl v5.18.2)' -H 'X-File: lua-resty-s3uploader-1.1.1.tar.gz' -H 'X-File-Checksum: b90ce99dbc44c0cbc3008fe39b5c744d' -H 'X-Account: lilien1010' -H 'X-Token: ******' -T 'lua-resty-s3uploader-1.1.1.tar.gz' 'https://opm.openresty.org/api/pkg/upload'
`

**Comment by agentzh** [comment]
@lilien1010 You should have used three backticks instead of just one. Your quoted code block is unreadable due to the messed up new lines.

**Comment by agentzh** [comment]
@lilien1010 You haven't replied to my previous comment:

>  I didn't see any related error logs on the server side. Have tried multiple times?
> 
> Also, what is the output of the command `curl https://opm.openresty.org/|grep pgmoon` on your side?

**Comment by lilien1010** [comment]
` web_install git:(master) curl https://opm.openresty.org/ |grep pgmoon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28789    0 28789    0     0   2456      0 --:--:--  0:00:11 --:--:--  6869
            <a href="https://github.com/agentzh/pgmoon/tree/agentzh">
            agentzh/pgmoon
            agentzh/pgmoon
            agentzh/pgmoon
            agentzh/pgmoon
            agentzh/pgmoon
            agentzh/pgmoon
➜  web_install git:(master)
`

**Comment by agentzh** [comment]
@lilien1010 Your comment is unreadable (see it yourself)...

**Comment by agentzh** [comment]
@lilien1010 Use

    ```
    ...
    ```

instead of

    `
    ...
    `

**Comment by agentzh** [comment]
@lilien1010 Your network looks okay.

**Comment by agentzh** [comment]
You are not expected to run `sudo` with `opm upload`.

**Comment by lilien1010** [comment]
it keep show error  
```
curl: (52) Empty reply from server
ERROR: failed to run command curl -sS .........
```

**Comment by agentzh** [comment]
No other output? Are you giving the complete output? Please do not just provide the last few lines. Please provide the complete output.

**Comment by agentzh** [comment]
Ensure you are using the latest `opm` from the github repo.

**Comment by lilien1010** [comment]
@agentzh  if I do not use sodu , it show error
```found license: BSD 3-Clause "New" or "Revised" license.
derived main_module file resty/s3uploader.lua
Can't opendir(/.DocumentRevisions-V100): Permission denied
 at /usr/local/openresty/bin/opm line 569.
Can't opendir(/.DocumentRevisions-V100 (from old Mac)): Permission denied
 at /usr/local/openresty/bin/opm line 569.
Can't opendir(/.fseventsd): Permission denied
 at /usr/local/openresty/bin/opm line 569.
Can't opendir(/.Spotlight-V100): Permission denied
 at /usr/local/openresty/bin/opm line 569.
Can't opendir(/.Trashes): Permission denied
 at /usr/local/openresty/bin/opm line 569.
```

and I just git pull from the openresty/opm  3 hours ago

**Comment by agentzh** [comment]
@lilien1010 Maybe you should look at the markdown format first? Your comment still messes up. You need a new line before and after

    ```

**Comment by lilien1010** [comment]
BTW I am use MacOS , sorry for the format problem I fixed it , and I think the complete output is too much ,can I send you a file through Email?

**Comment by agentzh** [comment]
@lilien1010 seems like your current working directory is wrong?

**Comment by agentzh** [comment]
@lilien1010 I'd share my session on my Macbook:

```
agentzh@mbp15 ~/work/opm-test-pkg $ opm upload
found license: BSD 2-Clause "Simplified" or "FreeBSD" license.
a opm-test-pkg-0.01
a opm-test-pkg-0.01/dist.ini
a opm-test-pkg-0.01/lib
a opm-test-pkg-0.01/README.md
a opm-test-pkg-0.01/lib/foo.lua
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Sat, 01 Oct 2016 04:42:53 GMT
Server: openresty
Content-Length: 134
Connection: keep-alive

File opm-test-pkg-0.01.tar.gz has been successfully uploaded and will be processed by the server shortly.
The uploaded task ID is 62.
```

**Comment by lilien1010** [comment]
this is the repo that I wanted to upload to opm
`lua-resty-s3uploader`

and I am runing `opm upload` in the `lua-resty-s3uploader` directory

**Comment by agentzh** [comment]
@lilien1010 Your current working directory must be the top directory of your Lua module source tree. It's strange that `opm` picks up many weird files and directories from your current working directory and I think you are just running `opm upload` from the wrong file system location.

**Comment by agentzh** [comment]
@lilien1010 Why should your `lua-resty-s3uploader` source tree contains the file `lua-resty-s3uploader-1.1.1/lib/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/node_modules/asar/node_modules/cuint/README.md`? What's that? You need a clean source tree.

**Comment by agentzh** [comment]
@lilien1010 Also, it seems that not all files or directories are accessible from your system account in your `lua-resty-s3uploader` source tree, which should not be the case. You must have messed up things in your own source tree?

**Comment by agentzh** [comment]
@lilien1010 Remove all those unrelated files from your `lua-resty-s3uploader` source tree, especially those under your `lib/` directory. Oh my god.

**Comment by lilien1010** [comment]
@agentzh 
after I run  `sudo opm build`  it generate files ` lua-resty-s3uploader-1.1.1*`  in the directry  lua-resty-s3uploader
```➜  lua-resty-s3uploader git:(master) 
total 78352
   16 README.md                             0 lua-resty-s3uploader-1.1.1            0 resty
    8 dist.ini                          78328 lua-resty-s3uploader-1.1.1.tar.gz
➜  lua-resty-s3uploader git:(master) ```

**Comment by agentzh** [comment]
I also have no idea about those directories like `/.DocumentRevisions-V100` and `/.Spotlight-V100`. Maybe you have weird symlinks in your source tree.

**Comment by agentzh** [comment]
@lilien1010 Your github comments above are not readable. Will you fix them up first? I suggest you read the help on the markdown syntax.

**Comment by lilien1010** [comment]
reload and I fixed

**Comment by agentzh** [comment]
@lilien1010 Why do you want to include `node_modules` under your `lib/` directory? Also, why do you use `sudo` to run `opm build`? If you use `sudo` to run `opm build`, then you must also use `sudo` to run `opm upload`.

**Comment by lilien1010** [comment]
maybe  becos I set the `doc_dir = /` in the dist.ini file,holy

**Comment by agentzh** [comment]
@lilien1010 Ah...That's crazy, man...

Okay, I think I'll simply reject absolute paths in the `lib_dir` and `doc_dir` values to catch such silly mistakes automatically.

**Comment by agentzh** [comment]
@lilien1010 Does `opm upload` work now after fixing your `lib_dir` and `doc_dir` values?

**Comment by lilien1010** [comment]
```
found license: BSD 3-Clause "New" or "Revised" license.
derived main_module file resty/s3uploader.lua
a lua-resty-s3uploader-1.1.1
a lua-resty-s3uploader-1.1.1/dist.ini
a lua-resty-s3uploader-1.1.1/lib
a lua-resty-s3uploader-1.1.1/README.md
a lua-resty-s3uploader-1.1.1/lib/README.md
a lua-resty-s3uploader-1.1.1/lib/s3uploader.lua
a lua-resty-s3uploader-1.1.1/lib/test.lua
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Server: YunFanCDN
Date: Sat, 01 Oct 2016 05:10:04 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-CDN-ReqID: CkNLQDd5V+9FKvAAB
Accept-Ranges: bytes
Oct-Response-Info: 0000000004500046016960170100001
YF-ID: yhkxx1b006105v
YF-ID: azjhz1s007959p
YF-ID: czjnb1a008052p
Oct-Upstream: 52.76.49.101,47.90.56.105,183.129.179.59,120.199.80.52
YF-ID: csdjn1a004201p

File lua-resty-s3uploader-1.1.1.tar.gz has been successfully uploaded and will be processed by the server shortly.
The uploaded task ID is 64.
```

Finished!!

**Comment by agentzh** [comment]
@lilien1010 Finally! Congrats! I've just committed a change in `opm` that makes `opm` rejects absolute path values in `lib_dir`, `doc_dir`, and `main_module`.
