### ISSUE TITLE
no namespace was used when `opm install`

### ISSUE THREAD

**Issue by sumory** [openresty/opm#18]
i just tried to package several versions of my framework(lor).  i found there may be a potential problem with `opm install`. 

if i use `opm install sumory/lor=0.2.0` to install, `site/lualib` will look like this:

```
├── index.lua
├── lib
└── resty
    └── ...
```

both the `index.lua` file and `lib` dir are belong to `lor`. they directly occupied the position under `lualib`.

so  i finally packaged another version to avoid this,  `opm install sumory/lor=0.2.2`：

```
├── lor
│   ├── index.lua
│   └── lib
└── resty
    └── ...
```

is this a problem? or i just didn't use `opm` with a better practice?

**Comment by agentzh** [comment]
You define your own namespace by using intermediate directories. See the standard OpenResty Lua libraries for real world examples. Opm doses not add your package name automatically and forcibly as the top level namespace.

**Comment by sumory** [comment]
another bad case:

i installed `opm install starjun/dynamic_balancer` first, and then the file `site/lualib/resty/random.lua` was  occupied.

for now, everything looks ok:

```
[12:24]root:/data/workspace # opm install starjun/dynamic_balancer
* Fetching starjun/dynamic_balancer
  Downloading https://opm.openresty.org/api/pkg/tarball/starjun/dynamic_balancer-1.0.1.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4651  100  4651    0     0   2519      0  0:00:01  0:00:01 --:--:--  2519
Package starjun/dynamic_balancer 1.0.1 installed successfully.
```

after a while, when i install another package `opm install openresty/lua-resty-string`, the following error occured:

```
[12:24]root:/data/workspace # opm install openresty/lua-resty-string
* Fetching openresty/lua-resty-string
  Downloading https://opm.openresty.org/api/pkg/tarball/openresty/lua-resty-string-0.09.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6163  100  6163    0     0   6822      0 --:--:-- --:--:-- --:--:--  6817
ERROR: file resty/random.lua in package openresty/lua-resty-string already appears in the previously installed package dynamic_balancer.
```

**Comment by sumory** [comment]
i'm getting confused that it's impossible for every user to build and upload the package as "standard OpenResty Lua libraries", e.g. lua-resty-string
 
maybe we should consider a proposal or specification to give some good examples about how to build opm packages, or we should redesign some machanism about opm.

**Comment by agentzh** [comment]
@sumory I don't see any issues in `opm` itself. The `opm` tool complaints about the right thing. It does not make sense to install two packages which both ship with the same file name (and path). You are allowed to override the standard OpenResty library files, though, but not those standard OpenResty libraries installed via `opm`. The true builtin OpenResty libraries are stored in a different location (`<openresty-prefix>/lualib`) than 3rd-party libraries.

**Comment by agentzh** [comment]
@sumory BTW, you should not install `openresty/lua-resty-string` since lua-resty-string is already shipped with OpenResty. Unless you need a newer version. But nevertheless, if a 3rd-party module has `resty/random.lua`, then it will shadow `resty/random.lua` shipped with your OpenResty installation.

**Comment by agentzh** [comment]
@sumory It's bad practice for 3rd-party OPM module developers to ship a Lua module that overrides the standard module files though `opm` does not prohibit. If it upsets you (as a user), then you should really report the problem to the author of that OPM module (`starjun/dynamic_balancer` in this case). I don't think there's anything to be done on our (`opm`) side.

**Comment by sumory** [comment]
if i want to use two  3rd-party modules(module A and module B) and unfortunately they both occupy the `site/lualib/resty/abc.lua` path, i should remove one module or ask the authors to rename it?

**Comment by agentzh** [comment]
@sumory Of course.
