### ISSUE TITLE
`Opmfile` and `Opmfile.lock`?

### ISSUE THREAD

**Issue by sinogermany** [openresty/opm#19]
New to the `opm` world. 
Is it worth having an `Opmfile` and even an `Opmfile.lock`?
Not sure if it's a trivial thing or not...
Feel free to close this issue as "will not fix" if it's not relevant.

**Comment by agentzh** [comment]
What do you mean? We already have a lock file under ~/.opm/ to avoid concurrent opm sessions from the same user. But maybe we should make it system wide.

**Comment by sinogermany** [comment]
> What do you mean? We already have a lock file under ~/.opm/ to avoid concurrent opm sessions from the same user. But maybe we should make it system wide.

Sorry for the confusion...

I was just wondering if it's possible to have a `.opm_packages` locally to a project, like:
- `package.json` being installed into `npm_packages`.
- `Gemfile` but installed locally with `bundle install --path vendor/bundle`.

Let's assume I'm using 2 version of `lua-resty-mysql` to write 2 apps.
With that option I'll be able to manage the dependencies in the project scope instead of a per-user scope or global scope.

**Comment by agentzh** [comment]
Have you checked out opm's --cwd option?

**Comment by sinogermany** [comment]
> Have you checked out opm's --cwd option?

Cool thanks :) Exactly what I'm looking for. Can't believe I missed that.
Please close this issue, and thanks again. Cheers!
