### ISSUE TITLE
how the opm handle the dependencies

### ISSUE THREAD

**Issue by monkindey** [openresty/opm#2]
eg:

module **A** depend module **B**
module **C** depend module **B**

when i download the **A** and **C**,
will download **B** twice?

**Comment by agentzh** [comment]
@monkindey Please do not use Chinese here. This place is considered English only.

Regarding your question, no, there will be no duplicate installation of B since when C is being installed, opm would find that B is already installed (because A has been installed).

**Comment by monkindey** [comment]
Thank you for your prompt reply

Sorry, because i press the **Enter** carelessly, so submit the Chinese version.

so I think how the opm handle the dependencies is to make the dependencies in a **flat** way instead of in a **nested** way. 

Can I brew install the opm ?

**Comment by agentzh** [comment]
@monkindey If you want to install different versions of the same package, then you should specify the `--cwd` option and install packages in the current working directory. This should be the "nested" way you are saying I suppose.

We may provide OpenResty's own homebrew repository sometime in the future (or just hijack the existing "openresty" brew maintained by some 3rd-party people if it's feasible).

**Comment by agentzh** [comment]
Consider it resolved.
