### ISSUE TITLE
About command names

### ISSUE THREAD

**Issue by bungle** [openresty/opm#23]
I think the `opm update` vs. `opm upgrade PACKAGE...` is confusing. Most package managers use `update` to update local package caches, and `upgrade` to update the packages to the latest version. Well, opm doesn't maintain (at least currently) a local package cache, so my suggestion would be just to have `opm update [PACKAGE...]` (`upgrade` can be left as an alias for this).

Also `opm get` is a bit weird choice, why not use a more common `install` (`get` can be left as an alias for this, also for `remove` we could add `uninstall` alias, and for `info` we could add alias `show`)?

What do you think?

**Comment by bungle** [comment]
Also it seems that `opm help` and `opm --help` and `opm -h` all work, but other commands only work without `--`, and have no short notation `-`.

**Comment by agentzh** [comment]
@bungle Well, the `update` and `upgrade` command semantics are exactly the same as Redhat's `yum` system. Also, it's also used by homebrew. I'm not sure where your `most package managers` come from. The only manager that fits your semantics to my knowledge is `apt-get`.

**Comment by agentzh** [comment]
@bungle BTW, we do have `install` as an alias for `get`. And also `uninstall` for `remove. They both work. They are not documented by intention since we want to recommend the canonical usage.

**Comment by bungle** [comment]
Well, `brew update`doesn't update anything, only caches. Same as `apt`. Also my favorite package manager `rudix` follows this. Also `npm`... but whatever, it just made more sense to me, but I can live with this.

**Comment by agentzh** [comment]
We do not cache any package indexes locally, so updating the cache just does not make any sense for us ;)

**Comment by bungle** [comment]
I know that and especially for that reason it makes little sense to me to have two different words here. You start to think how they differ, and after some research you find that they are the same, only that the other gets some more arguments.
