### ISSUE TITLE
--cwd not flexible enough

### ISSUE THREAD

**Issue by bungle** [openresty/opm#24]
`--cwd` option is defined as:

```
--cwd       Install into the current working directory under ./resty_modules/
            instead of the system-wide OpenResty installation tree contaning
            this tool.
```

This `./resty_modules/` cannot be configured (`.opmrc`: `cwd = lib/vendor`) or passed as argument value (`opm --cwd=lib/vendor`). Also if that is added, the `c` in `cwd` will lost a meaning as it might also accept full paths.

We could have:

``` bash
opm get     PACKAGE... [under PATH] # or
opm install PACKAGE... [under PATH]

# For example
opm install bungle/lua-resty-template under lib/vendor
```

**Comment by agentzh** [comment]
@bungle Well the `--cwd` option is not for flexibility but just for convenience. I was planning another `--install-dir=PATH` option instead for flexibility. Willing to submit a pull request for it? ;)

**Comment by bungle** [comment]
Ok, I can look at it.

**Comment by SirR4T** [comment]
I would like to take a shot at this, even though i haven't worked with perl. is that fine?
Also, this seems to raise a question: how should this option affect the `opm upgrade` command?

**Comment by agentzh** [comment]
@SirR4T In the same way as the current `--cwd` option, I think.

**Comment by SirR4T** [comment]
I'm using `File::Spec->rel2abs(...)`, because I expect the given values could be of the form `--install-dir=../../lib/`.

But then this doesn't seem to work with `--install-dir=~/local/lib/` though, because `rel2abs()` doesn't seem to resolve `~` to `$HOME`. Would that be required?

**Comment by agentzh** [comment]
@SirR4T It's your shell's responsibility to expand the `~` thing, not the command-line utility itself. Your notation just prevents your shell from doing its job of expanding `~`. You should use one of the following notations instead:

```bash
opm --install-dir ~/local/lib/
```

or

```bash
opm --install-dir=$HOME/local/lib/
```

**Comment by agentzh** [comment]
Now that `--install-dir` is merge, I'm closing this.
