### ISSUE TITLE
OPM is missing

### ISSUE THREAD

**Issue by dimitrovs** [openresty/opm#36]
The README says:

> The next OpenResty release (after 1.11.2.1) will include and install opm by default. 

My OpenResty version:

`# openresty -v
nginx version: openresty/1.11.2.2`

The result of running opm:

`# opm
-bash: opm: command not found`

**Comment by agentzh** [comment]
@dimitrovs How do you install your openresty?

If you install openresty from source, then you should add the `<prefix>/bin` to your PATH environment, as in

```
export PATH=/usr/local/openresty/bin:$PATH
```

assuming you are using the default openresty installation prefix, /usr/local/openresty/.

On the other hand, if you install openresty from our official Yum repositories, then you should install the `openresty-opm` package via yum, as in

```
sudo yum install openresty-opm
```

or

```
sudo dnf install openresty-opm
```

The `opm` tool installed from our Yum repository is visible to your PATH environment by default.
