### ISSUE TITLE
ERROR: luajit is required but is not available according to resty:

### ISSUE THREAD

**Issue by roadsigngit** [openresty/opm#44]
here is my path as below:

localhost:nlb huidizhao$ ls
bin		lualib		pod		site
luajit		nginx		resty.index	software

localhost:nlb huidizhao$ tree
.
├── bin
│   ├── md2pod.pl
│   ├── nginx-xml2pod
│   ├── openresty -> /Users/huidizhao/Documents/workspace/ssr/ssr/nlb/nginx/sbin/nginx
│   ├── opm
│   ├── resty
│   ├── restydoc
│   └── restydoc-index
├── luajit
│   ├── bin
│   │   ├── luajit -> luajit-2.1.0-beta2
│   │   └── luajit-2.1.0-beta2
│   ├── include
│   │   └── luajit-2.1
│   │       ├── lauxlib.h
│   │       ├── lua.h
│   │       ├── lua.hpp
│   │       ├── luaconf.h
│   │       ├── luajit.h
│   │       └── lualib.h
....
when i use opm to install lor plugins got the error : 

localhost:nlb huidizhao$ bin/opm install sumory/lor
* Fetching sumory/lor
  Downloading https://opm.openresty.org/api/pkg/tarball/sumory/lor-0.2.6.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16330  100 16330    0     0  18514      0 --:--:-- --:--:-- --:--:-- 18514
Package lua-resty-cookie-0.01 already installed.
* Fetching bungle/lua-resty-session >= 2.13
  Downloading https://opm.openresty.org/api/pkg/tarball/bungle/lua-resty-session-2.13.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33232  100 33232    0     0  60386      0 --:--:-- --:--:-- --:--:-- 60312
* Fetching openresty/lua-resty-string
  Downloading https://opm.openresty.org/api/pkg/tarball/openresty/lua-resty-string-0.09.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6163  100  6163    0     0  11830      0 --:--:-- --:--:-- --:--:-- 11851
sh: resty: command not found
**ERROR: luajit is required but is not available according to resty:**

addition message is ：
 1）there is no such path like /usr/local/openresty ...,because i have installed it in /User/....
 2) luajit home is defined in ~/.bash_profile

**Comment by agentzh** [comment]
@roadsigngit opm assumes the directory layout of OpenResty. For custom setup, you'll have to either 1) copy the OpenResty directory structure or 2) add the paths of your resty, nginx, and luajit executables to your PATH environment.

**Comment by agentzh** [comment]
@roadsigngit In this example, you are missing the `resty` command-line utility in your `PATH` environment, which is shipped with OpenResty or from its original github repository `openresty/resty-cli`.

**Comment by agentzh** [comment]
@roadsigngit It's generally a bad idea to use `opm` outside OpenResty since you are simply asking for troubles :) It could work but you need to very careful.

**Comment by roadsigngit** [comment]
thanks agentzh,i act on your suggestion and it works!

**Comment by Tinywan** [comment]
```bash
tinywan@tinywan:/opt/openresty/bin$ resty -e 'print("hello")'
hello
tinywan@tinywan:/opt/openresty/bin$ sudo ./opm get bungle/lua-resty-session
* Fetching bungle/lua-resty-session  
  Downloading https://opm.openresty.org/api/pkg/tarball/bungle/lua-resty-session-2.17.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33837  100 33837    0     0   273k      0 --:--:-- --:--:-- --:--:--  275k
* Fetching openresty/lua-resty-string  
  Downloading https://opm.openresty.org/api/pkg/tarball/openresty/lua-resty-string-0.09.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6163  100  6163    0     0  50432      0 --:--:-- --:--:-- --:--:-- 50516
sh: 1: resty: not found
ERROR: luajit is required but is not available according to resty:
```

**Comment by agentzh** [comment]
@Tinywan You know that sudo may have a different PATH env than your default shell session? You can try `sudo resty -e 'print("hello")'` instead.

**Comment by Tinywan** [comment]
@agentzh  thanks , 
```bash
tinywan@tinywan:~/Lua$ sudo resty -e 'print("hello")'
sudo: resty：找不到命令
```
## switch root install success
```bash
[root@/opt/openresty/bin]# ./opm --cwd get bungle/lua-resty-session
* Fetching bungle/lua-resty-session  
  Downloading https://opm.openresty.org/api/pkg/tarball/bungle/lua-resty-session-2.17.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33837  100 33837    0     0   261k      0 --:--:-- --:--:-- --:--:--  262k
* Fetching openresty/lua-resty-string  
  Downloading https://opm.openresty.org/api/pkg/tarball/openresty/lua-resty-string-0.09.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6163  100  6163    0     0  42986      0 --:--:-- --:--:-- --:--:-- 44338
Package openresty/lua-resty-string 0.09 installed successfully under /opt/openresty/bin/resty_modules/ .
Package bungle/lua-resty-session 2.17 installed successfully under /opt/openresty/bin/resty_modules/ .
```

**Comment by agentzh** [comment]
@Tinywan This is Linux basics. You should either change your suders file or just pass the `-E` option to the `sudo` command.

**Comment by Tinywan** [comment]
@agentzh thanks ,this is OK
```bash
su - root
vim /etc/sudoers
tinywan ALL=(ALL:ALL) ALL
wq!
```
