### ISSUE TITLE
Support for Creative Commons Licenses

### ISSUE THREAD

**Issue by bungle** [openresty/opm#5]
Maybe we should have support for:
https://creativecommons.org/licenses/

in

https://github.com/openresty/opm#license

(I suppose in the end we might supply things like static assets with this as well, like images, sounds, videos, and maybe stylesheets).

**Comment by agentzh** [comment]
@bungle Yeah, we can add the most common ones in this CC set. Pull requests welcome :)

**Comment by agentzh** [comment]
Consider it resolved.
