### ISSUE TITLE
"ERROR: luajit is required but is not available according to resty: "]

### ISSUE THREAD

**Issue by Phrozyn** [openresty/opm#52]
I'm having a similar problem to issue #44 
I see the following installed under openresty which was installed via RPM:

usr/local/lib/pkgconfig/luajit.pc
/usr/local/openresty/luajit
/usr/local/openresty/luajit/bin
/usr/local/openresty/luajit/include
/usr/local/openresty/luajit/lib
/usr/local/openresty/luajit/share
/usr/local/openresty/luajit/bin/luajit
/usr/local/openresty/luajit/bin/luajit-2.1.0-beta2
/usr/local/openresty/luajit/include/luajit-2.1
/usr/local/openresty/luajit/include/luajit-2.1/lauxlib.h
/usr/local/openresty/luajit/include/luajit-2.1/lua.h
/usr/local/openresty/luajit/include/luajit-2.1/lua.hpp
/usr/local/openresty/luajit/include/luajit-2.1/luaconf.h
/usr/local/openresty/luajit/include/luajit-2.1/luajit.h
/usr/local/openresty/luajit/include/luajit-2.1/lualib.h
/usr/local/openresty/luajit/lib/libluajit-5.1.so
/usr/local/openresty/luajit/lib/libluajit-5.1.so.2
/usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0
/usr/local/openresty/luajit/lib/lua
/usr/local/openresty/luajit/lib/pkgconfig
/usr/local/openresty/luajit/lib/lua/5.1
/usr/local/openresty/luajit/lib/pkgconfig/luajit.pc
/usr/local/openresty/luajit/share/lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2
/usr/local/openresty/luajit/share/lua/5.1
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/bc.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/bcsave.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_arm.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_arm64.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_arm64be.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_mips.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_mips64.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_mips64el.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_mipsel.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_ppc.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_x64.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dis_x86.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/dump.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/p.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/v.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/vmdef.lua
/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/jit/zone.lua
/usr/local/share/man/man1/luajit.1

Unlike the documentation states, resty-cli was not included in the package nor did it have an associated RPM, so I manually installed it and placed it's binaries in the /usr/local/openresty/bin/ directory. However, for some reason it's still not getting past the luajit part. Any help is appreciated.

**Comment by agentzh** [comment]
@Phrozyn You should install the openresty-resty package at the same time. the resty-cli tool is in a separate rpm package. See

http://openresty.org/en/rpm-packages.html

**Comment by agentzh** [comment]
@Phrozyn Similarly, opm is in the openresty-opm package. The default openresty package is minimal.

**Comment by agentzh** [comment]
@Phrozyn Ensure you have removed  your own copied scripts those will break things.

**Comment by Phrozyn** [comment]
Thanks!, I'll do this now and update on progress!

**Comment by agentzh** [comment]
@Phrozyn I've just noted that the openresty-opm package does not explicitly require deps like openresty-resty and openresty-doc on the rpm level. I've just fixed. You can try

```
sudo yum clean expire-cache
sudo yum upgrade openresty-opm  # or install
```

**Comment by Phrozyn** [comment]
it's working beautifully! Thanks so much for your help :) This can be closed :)
