### ISSUE TITLE
Is it possible to install lapis with opm?

### ISSUE THREAD

**Issue by tpimh** [openresty/opm#57]
I want to install [Lapis](http://leafo.net/lapis/). Can I use `opm` for it? If yes, how do I do it?

**Comment by agentzh** [comment]
@tpimh I think you should ask Lapis's authors or maintainers instead. Opm is just a platform for openresty library authors to share their work. We are not maintaining Lapis.

**Comment by tpimh** [comment]
Looks like Lapis already has an open issue for this: https://github.com/leafo/lapis/issues/571
So I'm closing this one, as it's not relevant to `opm` itself.
