### ISSUE TITLE
opm get jkeys089/lua-resty-hmac fails with ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by prashantchari** [openresty/opm#58]
Fetching jkeys089/lua-resty-hmac  
 gnutls_handshake() failed: Handshake failed
ERROR: failed to run command "curl -sS -i -A 'opm 0.0.4 (x86_64-linux-gnu-thread-multi, perl v5.22.1)' 'https://opm.openresty.org/api/pkg/fetch?account=jkeys089&name=lua-resty-hmac&op=&version='"

**Comment by prashantchari** [comment]
Issue appears to be fixed now.

**Comment by agentzh** [comment]
@prashantchari Yes, we were experiencing SSL related problems. Thanks for your report!
