### ISSUE TITLE
Unable to install package with an nginx static module(opentracing)

### ISSUE THREAD

**Issue by ncsibra** [openresty/opm#60]
I have an alpine docker image which contains openresty  1.13.6.1, compiled from tarball.
I added [nginx-opentracing](https://github.com/opentracing-contrib/nginx-opentracing) with Jaeger as a static module, it works fine by itself.
Now I want to install a package with opm, but it fails, because resty cli unable to detect nginx version.
My PATH contains the openresty bin pathes, the problem is, that Jaeger opentracing needs a directive in the config or dies at the start. I have this directive and nginx starts fine, but seems like opm does not use that config file.
The problem is here: https://github.com/openresty/opm/blob/master/bin/opm#L1036
```
/ # opm get thibaultcha/lua-resty-jit-uuid
* Fetching thibaultcha/lua-resty-jit-uuid
  Downloading https://opm.openresty.org/api/pkg/tarball/thibaultcha/lua-resty-jit-uuid-0.0.7.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6398  100  6398    0     0  44124      0 --:--:-- --:--:-- --:--:-- 43821
nginx: [error] `jaeger_service_name` must be specified
ERROR: luajit is required but is not available according to resty:
/ # echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin
/ # which nginx
/usr/local/openresty/nginx/sbin/nginx
/ # which resty
/usr/local/openresty/bin/resty
/ # which luajit
/usr/local/openresty/luajit/bin/luajit
/ # resty -e 'print(ngx.config.nginx_version)'
nginx: [error] `jaeger_service_name` must be specified
/ # resty --http-conf "jaeger_service_name 'abc';" -e 'print(ngx.config.nginx_version)'
1013006
/ # nginx
2018/02/24 17:13:11 [notice] 32#0: using the "epoll" event method
2018/02/24 17:13:11 [notice] 32#0: openresty/1.13.6.1
2018/02/24 17:13:11 [notice] 32#0: built by gcc 6.4.0 (Alpine 6.4.0)
2018/02/24 17:13:11 [notice] 32#0: OS: Linux 4.13.0-36-generic
2018/02/24 17:13:11 [notice] 32#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2018/02/24 17:13:11 [notice] 32#0: start worker processes
2018/02/24 17:13:11 [notice] 32#0: start worker process 33
2018/02/24 17:13:11 [notice] 32#0: start cache manager process 34
```
As you can see, I can solve the problem with resty cli, but doesn't know how to solve it with opm.
Compile it as a dynamic module would solve the problem, but I always need the opentracing module, so it feels more natural to me to add it as a static one and I assume this isn't the only module which could cause a problem like this.
The config file is in the default location at `/usr/local/openresty/nginx/conf/nginx.conf`.
Am I doing something wrong? Should opm use the config file by itself?
Or is it a known limitation?

**Comment by agentzh** [comment]
@ncsibra I think you should contact the author of that module instead. We know nothing about that 3rd-party module or Lua library, so we cannot really help here.

Regarding to the following error message:

> ERROR: luajit is required but is not available according to resty

Seems like you are not using opm in your OpenResty installation tree. The opm tool does not look for luajit from the PATH, but from the installation tree the opm tool itself is in, via relative paths. So if you are not using the right opm from the right place, then you will see this error.

**Comment by agentzh** [comment]
@ncsibra OK, I see the real cause is that your `jaeger` nginx module requires you to always configure its configuration directive, which definitely breaks the resty-cli toolchain. You should really contact that module's developer instead if you really want to enable it at all times since it is a very unreasonable requirement even in the nginx world (nginx modules are not engaged when they are not configured in nginx.conf at all).

**Comment by agentzh** [comment]
@ncsibra I don't think it's our issue, but your `jaeger` 3rd-party nginx module's design mistake.

**Comment by ncsibra** [comment]
Ok, thanks, we'll see.
