### ISSUE TITLE
What does it mean to extract the version number of the current package?

### ISSUE THREAD

**Issue by bungle** [openresty/opm#7]
`main_module`is documented as:
https://github.com/openresty/opm#main_module

What does it mean that `The opm build command reads the "main module" file to extract the version number of the current package`?

What does it actually do?

Does it `require` the main Lua module, and tries to read some fields out of it? What are these fields?

**Comment by agentzh** [comment]
@bungle It uses regexes to scan the Lua source statically. Added the more docs to README to clarify that. Please let me know if it needs further treatment. Thanks!
