### ISSUE TITLE
opm failed to index package

### ISSUE THREAD

**Issue by fffonion** [openresty/opm#76]
Hi, it seems my last three submission to opm encounted trouble (copied from email):

```
I just ran into a fatal error while processing your package fffonion/lua-resty-openssl 0.5.2, which was recently uploaded at 2020-02-09 06:21:42.640466+00 as Task No. 749.

The details are as follows. If you still have no clues about the issue, please concact us through <info@openresty.org>.

Please remember to provide this mail for the reference. Thank you!

------
failed to run "opm server-build":
found license: BSD 3-Clause "New" or "Revised" license.
extracted verson number 0.5.2 from main_module file lib/resty/openssl.lua.
failed to run command "/usr/local/openresty/bin/md2pod.pl -o /opm/incoming/fffonion/lua-resty-openssl-0.5.2/lua-resty-openssl-0.5.2.opm/pod/lua-resty-openssl-0.5.2/lua-resty-openssl-0.5.2.pod /opm/incoming/fffonion/lua-resty-openssl-0.5.2/README.md": No such file or directory
ERROR: failed to run command /usr/local/openresty/bin/restydoc-index --outdir 'lua-resty-openssl-0.5.2.opm' .
```

Local run of `opm server-build` suceeded.

**Comment by agentzh** [comment]
@fffonion It might be caused by disk shortage at that time. I just tested a simple package uploading and it was indexed successfully. Will you please try again? Please let me know if the problem still persists. Thanks!

**Comment by fffonion** [comment]
Hi @agentzh, thank you for looking into this. I'm able to upload a different package but still not the package above, it failed with same error.

**Comment by xiaocang** [comment]
@fffonion May be something went wrong with the server.
I just fork your repo and uploaded it successfully. Could you try it again?

**Comment by fffonion** [comment]
@xiaocang I just uploaded again but still no luck. Also tried: same version with different package name and previous succeeded version (0.5.0) but with a different package name. 🤔

**Comment by xiaocang** [comment]
@fffonion I'm sorry about this. 
I just received the failed upload file that opm server gave me. It seems there should be something wrong with the opm server.

**Comment by xiaocang** [comment]
> @fffonion I'm sorry about this.
> I just received the email from opm server that failed to upload the file. It seems there should be something wrong with the opm server.

I tried to fix the problem of the opm server: permission issues during build-server execution
I verified multiple times and it should have been fixed.

**Comment by fffonion** [comment]
@xiaocang I can upload on my side as well 👍 Thank you for looking into this!

**Comment by fffonion** [comment]
Hi @xiaocang , I'm reopening this issue as it seems the same issue come back again. The error message is identical as before:

```
I am the indexer program on the OPM package server.

I just ran into a fatal error while processing your package fffonion/lua-resty-openssl 0.6.5, which was recently uploaded at 2020-09-25 08:20:24.518728+00 as Task No. 967.

The details are as follows. If you still have no clues about the issue, please concact us through <info@openresty.org>.

Please remember to provide this mail for the reference. Thank you!

------
failed to run "opm server-build":
found license: BSD 3-Clause "New" or "Revised" license.
extracted verson number 0.6.5 from main_module file lib/resty/openssl.lua.
failed to run command "/usr/local/openresty/bin/md2pod.pl -o /opm/incoming/fffonion/lua-resty-openssl-0.6.5/lua-resty-openssl-0.6.5.opm/pod/lua-resty-openssl-0.6.5/lua-resty-openssl-0.6.5.pod /opm/incoming/fffonion/lua-resty-openssl-0.6.5/README.md": No such file or directory
ERROR: failed to run command /usr/local/openresty/bin/restydoc-index --outdir 'lua-resty-openssl-0.6.5.opm' .

------

Best regards,
OPM Indexer
```

**Comment by xiaocang** [comment]
Thanks for the report, I'll check the service.

**Comment by xlibor** [comment]
@fffonion  It is related to the execution of the `server-build` takes a long time to exceed the explicit limit. In detail, the README.md file in this package is relatively long. After raising the upper limit, the index task passed. If you have similar problems next time, please report again.

**Comment by fffonion** [comment]
@xlibor I see, thank you for looking into and fixing this!
