### ISSUE TITLE
OPM pending to index packages

### ISSUE THREAD

**Issue by keyur9** [openresty/opm#77]
Hello, 

The packages are not getting indexed and it's in pending status for over a week. 

Is there any way to resolve that? Any help is much appreciated.

Thank you,

**Comment by agentzh** [comment]
@keyur9 Thanks for the report. We'll look into it.

**Comment by xiaocang** [comment]
@keyur9 Sorry, the opm service has failed and it is now fixed.

**Comment by keyur9** [comment]
Hello @xiaocang thank you for fixing it. I have a couple of questions:

- I see there are a few packages that are in a failed state. Is there a way to process that in case if want to access the older version at some point?
- It looks like you forked the repo `xiaocang/lua-resty-moesif` and indexed it but `Moesif/lua-resty-moesif` is still in failed status. Is there any way to index that, so I could use that package instead of `xiaocang/lua-resty-moesif`. If there are any additional changes that need to be made in `Moesif/lua-resty-moesif` in order for it to index, please let me know.

**Comment by agentzh** [comment]
@keyur9 That is still a TODO and not yet supported. For now it requires bumping the version number and release a new version.

**Comment by keyur9** [comment]
Thank you @agentzh. I'll bump the version and release a new version.
